spring:
  application.name: rate-limiter
  port: 8080
  redis:
    host: localhost
    port: 6379
  datasource:
    url: jdbc:h2:mem:jobrunr
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
jobrunr:
  dashboard.enabled: true
  background-job-server.enabled: true
